version: '3'

services:
  metabase-pdf-generator:
    build: .
    volumes:
      - ./reports:/app/reports
    environment:
      - TZ=UTC
      - METABASE_URL=https://metabase.example.com/public/dashboard/123456
      - REPORT_TITLE=Daily Report
      - SEND_EMAIL=true
      - EMAIL_FROM=sender@example.com
      - EMAIL_TO=recipient@example.com
      - SMTP_HOST=127.0.0.1
      - SMTP_PORT=25
      - DELETE_AFTER_EMAIL=true
    restart: unless-stopped